package com.snh.snhseller.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.snh.snhseller.bean.beanDao.AearBean;
import com.snh.snhseller.bean.salebean.SaleUserBean;

import com.snh.snhseller.greendao.AearBeanDao;
import com.snh.snhseller.greendao.SaleUserBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig aearBeanDaoConfig;
    private final DaoConfig saleUserBeanDaoConfig;

    private final AearBeanDao aearBeanDao;
    private final SaleUserBeanDao saleUserBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        aearBeanDaoConfig = daoConfigMap.get(AearBeanDao.class).clone();
        aearBeanDaoConfig.initIdentityScope(type);

        saleUserBeanDaoConfig = daoConfigMap.get(SaleUserBeanDao.class).clone();
        saleUserBeanDaoConfig.initIdentityScope(type);

        aearBeanDao = new AearBeanDao(aearBeanDaoConfig, this);
        saleUserBeanDao = new SaleUserBeanDao(saleUserBeanDaoConfig, this);

        registerDao(AearBean.class, aearBeanDao);
        registerDao(SaleUserBean.class, saleUserBeanDao);
    }
    
    public void clear() {
        aearBeanDaoConfig.clearIdentityScope();
        saleUserBeanDaoConfig.clearIdentityScope();
    }

    public AearBeanDao getAearBeanDao() {
        return aearBeanDao;
    }

    public SaleUserBeanDao getSaleUserBeanDao() {
        return saleUserBeanDao;
    }

}
